- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - manilaclient-dsvm-neutron-functional
        - rally-dsvm-manila-multibackend:
            voting: false
        - rally-dsvm-manila-multibackend-no-ss:
            voting: false
    gate:
      jobs:
        - manilaclient-dsvm-neutron-functional

- job:
    name: manilaclient-dsvm-neutron-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/manilaclient-dsvm-neutron-functional/run.yaml
    post-run: playbooks/legacy/manilaclient-dsvm-neutron-functional/post.yaml
    timeout: 5400
    required-projects:
      - openstack/devstack-gate
      - openstack/manila
      - openstack/neutron
      - openstack/python-manilaclient
      - openstack/manila-tempest-plugin
