- hosts: primary

  roles:
    - role: fetch-tox-output
      zuul_work_dir: "{{ ansible_user_dir }}/workspace/python-manilaclient"
      tox_envlist: functional
    - role: fetch-subunit-output
      zuul_work_dir: "{{ ansible_user_dir }}/workspace/python-manilaclient"
      tox_envlist: functional
  tasks:
    - name: Copy job config files
      synchronize:
        src: "{{ ansible_user_dir }}/workspace/python-manilaclient/etc"
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        verify_host: true
    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: "{{ ansible_user_dir }}/workspace/"
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
