- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - python-manilaclient-functional
        - manila-rally-ss:
            voting: false
        - python-manilaclient-functional-fips:
            voting: false
        - manila-rally-no-ss:
            voting: false
    gate:
      jobs:
        - python-manilaclient-functional
