- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - python-manilaclient-functional
        - manila-rally-ss:
            voting: false
        - manila-rally-no-ss:
            voting: false
        - openstack-tox-lower-constraints:
            branches: master
    gate:
      jobs:
        - python-manilaclient-functional
